### ISSUE TITLE
using EventGrid in TcHMI-Popups

### ISSUE THREAD

**Issue by AndertBos** [PerfectlyMint/TwinCAT-HMI-Popups#1]
In my dialogue that pops up with TcHMI-Popups I have placed an EventGrid. The buttons in the EventGrid are operable, but I can't select a separate alarm in the list
![PopUp](https://user-images.githubusercontent.com/33857800/163542556-b0ce68d7-8ea0-4ddd-b220-d9e0ea9c1dc6.png)
.

**Comment by PerfectlyMint** [comment]
Hi, thanks for yor report. This should be fixed in the 1.1.6 version. (Also textboxes work in 1.12.754.4)
